site_name: experiment-server
site_url: https://example.com/
repo_url: https://github.com/ahmed-shariff/experiment_server/
repo_name: 'GitHub'

theme:
  name: material
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
            heading_level: 2
            parameter_headings: true
            show_symbol_type_heading: true

nav:
  - Introduction: 'index.md'
  - Documentation: 'documentation.md'

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences 